name: Call Bomber Automation

on:
  workflow_dispatch:
  push:

jobs:
  run-call-bomber:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: git clone https://github.com/oldhacker786/CALL-BOMBER.git

      - name: Execute script with phone number input
        run: |
          cd CALL-BOMBER
          echo "03242772003" | bash call_bomber.sh
